import { AUTOMATION_TRIGGERS, type AutomationTrigger } from "@/lib/emailAutomations";
export type DraftTemplateSeed = { key: string; name: string; type: string; trigger: AutomationTrigger; subject: string; body: string; ctaLabel?: string; ctaUrl?: string };
function monthly(key: string, month: string, trigger: AutomationTrigger): DraftTemplateSeed { return { key, type: "monthly", name: `${month} first Tuesday update`, trigger, subject: `${month} stock and sourcing update from Combay`, body: `Dear {{name}},\n\nThis is our ${month} Combay update. If you are planning procurement, maintenance or replacement sourcing, send us the SKU, MPN, manufacturer or equipment details and we will check availability.`, ctaLabel: "Browse stock", ctaUrl: "/shop" }; }
export const SYSTEM_DRAFT_TEMPLATES: DraftTemplateSeed[] = [
  { key: "welcome", type: "transactional", name: "New user welcome", trigger: "NEW_SIGNUP", subject: "Welcome to Combay", body: "Dear {{name}},\n\nThank you for verifying your Combay account. Your portal is ready for quotes, orders, returns and support.\n\nReply with any SKU, MPN, manufacturer or application details if you need help sourcing equipment.", ctaLabel: "Open customer portal", ctaUrl: "/portal" },
  { key: "new-user-discount", type: "new_user_discount", name: "New user discount", trigger: "NEW_SIGNUP", subject: "Your Combay account is ready", body: "Dear {{name}},\n\nWelcome to Combay. As a new customer, you can use code <strong>{{promotionCode}}</strong> at checkout where eligible.\n\nBrowse current stock or reply with the item details you need us to source.", ctaLabel: "Browse stock", ctaUrl: "/shop" },
  { key: "first-order", type: "transactional", name: "First order thank-you", trigger: "FIRST_ORDER_COMPLETED", subject: "Thank you for your first Combay order {{orderNumber}}", body: "Dear {{name}},\n\nThank you for placing your first order with Combay. Payment has been received for <strong>{{orderNumber}}</strong>.\n\nOur team will prepare the goods and add dispatch details to your portal once available.", ctaLabel: "View order", ctaUrl: "/portal/orders" },
  monthly("monthly-january", "January", "MONTHLY_JANUARY"), monthly("monthly-february", "February", "MONTHLY_FEBRUARY"), monthly("monthly-march", "March", "MONTHLY_MARCH"), monthly("monthly-april", "April", "MONTHLY_APRIL"), monthly("monthly-may", "May", "MONTHLY_MAY"), monthly("monthly-june", "June", "MONTHLY_JUNE"), monthly("monthly-july", "July", "MONTHLY_JULY"), monthly("monthly-august", "August", "MONTHLY_AUGUST"), monthly("monthly-september", "September", "MONTHLY_SEPTEMBER"), monthly("monthly-october", "October", "MONTHLY_OCTOBER"), monthly("monthly-november", "November", "MONTHLY_NOVEMBER"), monthly("monthly-december", "December", "MONTHLY_DECEMBER"),
  { key: "new-year", type: "seasonal", name: "New Year message", trigger: "NEW_YEAR", subject: "New Year sourcing support from Combay", body: "Dear {{name}},\n\nAs the year closes, thank you for using Combay. If you are planning January procurement, equipment replacement or obsolete spare sourcing, send us your list and we will help check availability.", ctaLabel: "Contact Combay", ctaUrl: "/contact" },
  { key: "summer", type: "seasonal", name: "Summer campaign", trigger: "SUMMER", subject: "Summer industrial stock availability at Combay", body: "Dear {{name}},\n\nOur summer stock update is now available. Combay can help with automation spares, controls, test equipment, laboratory equipment and replacement sourcing during planned maintenance periods.", ctaLabel: "View stock", ctaUrl: "/shop" },
  { key: "easter", type: "seasonal", name: "Easter reminder", trigger: "EASTER", subject: "Easter period sourcing support from Combay", body: "Dear {{name}},\n\nAhead of the Easter period, please let us know if you need support sourcing industrial automation, electrical, scientific or test equipment before scheduled downtime.", ctaLabel: "Contact Combay", ctaUrl: "/contact" },
  { key: "christmas", type: "seasonal", name: "Christmas message", trigger: "CHRISTMAS", subject: "Christmas stock and support update from Combay", body: "Dear {{name}},\n\nThank you for working with Combay. During the Christmas period, we can still help with stock enquiries, urgent replacement sourcing and post-holiday procurement planning.", ctaLabel: "Browse stock", ctaUrl: "/shop" },
  { key: "boxing-day", type: "seasonal", name: "Boxing Day stock update", trigger: "BOXING_DAY", subject: "Boxing Day stock availability from Combay", body: "Dear {{name}},\n\nSelected industrial, automation, laboratory and test equipment remains available through Combay. If you are planning replacement stock, repairs or new-year procurement, send us the details and we will help source suitable options.", ctaLabel: "View available stock", ctaUrl: "/shop" },
  { key: "new-stock", type: "new_stock", name: "New stock arrival", trigger: "ORDER_COMPLETED", subject: "New industrial stock has arrived at Combay", body: "Dear {{name}},\n\nWe have added further automation, controls, test and scientific equipment to the website. If you are looking for a particular SKU, MPN, manufacturer or obsolete spare, reply to this email and our team will check availability.", ctaLabel: "View new stock", ctaUrl: "/shop" },
];
export const DRAFT_TEMPLATE_TYPES = [ { value: "transactional", label: "Transactional" }, { value: "new_user_discount", label: "New user discount" }, { value: "monthly", label: "Monthly campaign" }, { value: "seasonal", label: "Seasonal campaign" }, { value: "new_stock", label: "New stock arrival" }, { value: "service", label: "Repair/service" }, { value: "general", label: "General" } ];
export function isValidTemplateTrigger(value: unknown): value is AutomationTrigger { return AUTOMATION_TRIGGERS.includes(value as AutomationTrigger); }
