"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import TopBar from "@/components/layout/TopBar";
import Navigation from "@/components/layout/Navigation";
import Footer from "@/components/layout/Footer";
import { cmsBackgroundStyle } from "@/lib/cmsBackground";
import type { SiteContent, FaqItem } from "@/lib/siteContent";
import VisualWidgetZone from "@/components/visual-cms/VisualWidgetZone";
const fallback:any={faq:{eyebrow:"Support",heading:"Frequently Asked Questions",body:"Can't find what you need? Email info@combay.co.uk and we'll respond within 24 hours.",backgroundImageUrl:"",groups:[{key:"sales",label:"Sales",items:[{question:"What is your delivery time?",answer:"UK deliveries typically take 1–3 working days."}]}],ctaHeading:"Still have questions?",ctaBody:"Our team responds within 24 hours.",ctaLabel:"Contact Us →",ctaHref:"/contact"},contact:{salesEmail:"sales@combay.co.uk",infoEmail:"info@combay.co.uk",phone:"+44 7340 383334",location:"Chelmsford, Essex, UK",whatsapp:"447340383334"},footer:{description:"UK-based industrial equipment specialists.",backgroundImageUrl:""}};
function Accordion({ items, groupKey }: { items:FaqItem[]; groupKey:string }) { const [open,setOpen]=useState<number|null>(0); const [visualCms,setVisualCms]=useState(false); useEffect(()=>{setVisualCms(new URLSearchParams(window.location.search).get("vcms")==="1")},[]); return <div className="space-y-2" data-vcms-collection={`faq.groupItems:${groupKey}`}>{items.map((item,i)=>{const expanded=visualCms||open===i; return <div key={`${item.question}-${i}`} data-vcms-item={`faq.groupItems:${groupKey}`} data-vcms-index={i} className="border border-gray-200 rounded-lg overflow-hidden bg-white"><button onClick={()=>setOpen(open===i?null:i)} className="w-full px-5 py-4 flex items-center justify-between text-left hover:bg-gray-50"><span className="font-display font-600 text-navy-900 text-sm">{item.question}</span><span className="text-accent text-lg">{expanded?"–":"+"}</span></button>{expanded&&<div className="px-5 pb-4 text-gray-600 text-sm leading-relaxed border-t border-gray-100 pt-3">{visualCms?<p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-gray-400">Answer</p>:null}<p>{item.answer}</p></div>}</div>})}</div> }
export default function FaqPage(){const[content,setContent]=useState<SiteContent>(fallback);const[tab,setTab]=useState("sales");useEffect(()=>{fetch('/api/admin/content',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d?.content){setContent(d.content);setTab(d.content.faq?.groups?.[0]?.key||'sales')}}).catch(()=>null)},[]);const faq=content.faq;const group=faq.groups.find(g=>g.key===tab)||faq.groups[0];return <main><TopBar/><Navigation/><VisualWidgetZone pageKey="faq" zone="top" widgets={content.visualWidgets?.["faq:top"] || []}/><section className="py-14 bg-white" style={cmsBackgroundStyle(faq.backgroundImageUrl, 'rgba(255,255,255,.92)')}><div className="max-w-3xl mx-auto px-4"><p className="section-label">{faq.eyebrow}</p><h1 className="page-heading text-4xl mb-2">{faq.heading}</h1><p className="text-gray-500 mb-8 text-sm">{faq.body}</p><div className="flex flex-wrap gap-2 mb-8">{faq.groups.map(g=><button key={g.key} onClick={()=>setTab(g.key)} className={`font-display font-600 text-sm px-5 py-2.5 rounded-lg border transition-all ${tab===g.key?'bg-navy-900 text-white border-navy-900':'bg-white text-navy-800 border-gray-200 hover:border-navy-900'}`}>{g.label}</button>)}</div><Accordion items={group?.items||[]} groupKey={group?.key || "sales"}/><div className="mt-10 bg-gray-50 border border-gray-200 rounded-xl p-5 flex flex-col sm:flex-row items-start sm:items-center gap-4"><div className="flex-1"><p className="font-display font-700 text-navy-900 text-sm mb-1">{faq.ctaHeading}</p><p className="text-gray-500 text-xs">{faq.ctaBody}</p></div><Link href={faq.ctaHref} className="btn-primary flex-shrink-0 whitespace-nowrap">{faq.ctaLabel}</Link></div></div></section><VisualWidgetZone pageKey="faq" zone="beforeFooter" widgets={content.visualWidgets?.["faq:beforeFooter"] || []}/><Footer content={{description:content.footer.description,backgroundImageUrl:content.footer.backgroundImageUrl,contact:content.contact}}/></main>}
