import { NextResponse } from "next/server";
import { prisma, withDatabase } from "@/lib/db";
import { DRAFT_TEMPLATE_TYPES, SYSTEM_DRAFT_TEMPLATES, isValidTemplateTrigger } from "@/lib/marketingTemplates";
import { automationTriggerLabel, automationTriggerType } from "@/lib/emailAutomations";
export const dynamic = "force-dynamic";
function publicTemplate(template: any) { return { id: template.id, name: template.name, type: template.type || "general", trigger: template.trigger, triggerLabel: automationTriggerLabel(template.trigger), triggerType: automationTriggerType(template.trigger), subject: template.subject, body: template.body, ctaLabel: template.ctaLabel || "", ctaUrl: template.ctaUrl || "", isSystem: Boolean(template.isSystem), createdAt: template.createdAt?.toISOString?.() || template.createdAt }; }
function systemTemplates() { return SYSTEM_DRAFT_TEMPLATES.map((template) => publicTemplate({ id: `system:${template.key}`, ...template, isSystem: true, createdAt: new Date(0) })); }
function cleanTemplate(body: any) { const name = String(body.name || "").trim(); const type = String(body.type || "general").trim() || "general"; const trigger = isValidTemplateTrigger(body.trigger) ? body.trigger : null; const subject = String(body.subject || "").trim(); const bodyText = String(body.body || "").trim(); if (!name) throw new Error("Draft name is required."); if (!trigger) throw new Error("Choose a valid trigger for this draft."); if (!subject) throw new Error("Draft subject is required."); if (!bodyText) throw new Error("Draft body is required."); return { name, type, trigger, subject, body: bodyText, ctaLabel: body.ctaLabel ? String(body.ctaLabel).trim() : null, ctaUrl: body.ctaUrl ? String(body.ctaUrl).trim() : null, isSystem: false }; }
export async function GET() { const result = await withDatabase(async () => { const custom = await prisma.emailDraftTemplate.findMany({ orderBy: [{ type: "asc" }, { name: "asc" }] }); return custom.map(publicTemplate); }); if (!result.ok) return NextResponse.json({ ok: true, templates: systemTemplates(), types: DRAFT_TEMPLATE_TYPES, warning: result.reason }); return NextResponse.json({ ok: true, templates: [...systemTemplates(), ...result.data], types: DRAFT_TEMPLATE_TYPES }); }
export async function POST(request: Request) { const body = await request.json().catch(() => null); if (!body) return NextResponse.json({ ok: false, error: "Invalid draft data." }, { status: 400 }); try { const data = cleanTemplate(body); const result = await withDatabase(async () => prisma.emailDraftTemplate.create({ data })); if (!result.ok) return NextResponse.json({ ok: false, error: result.reason }, { status: 500 }); return NextResponse.json({ ok: true, template: publicTemplate(result.data) }); } catch (error) { return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : "Could not save draft." }, { status: 400 }); } }
