import Link from "next/link";
import type { CmsPage, SiteContent } from "@/lib/siteContent";

function Paragraphs({ text, className }: { text: string; className: string }) {
  const parts = String(text || "").split(/\n{1,}/).map((part) => part.trim()).filter(Boolean);
  if (!parts.length) return null;
  return <div className={className}>{parts.map((part, index) => <p key={index}>{part}</p>)}</div>;
}

type Contact = SiteContent["contact"];
export default function CmsPageLayout({ page, contact, children, formTitle }: { page: CmsPage; contact?: Contact; children?: React.ReactNode; formTitle?: string }) {
  const heroStyle = page.backgroundImageUrl ? { backgroundImage: `linear-gradient(rgba(3,14,33,.88),rgba(3,14,33,.88)), url(${page.backgroundImageUrl})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined;
  return <>
    <section className="bg-navy-950 text-white py-16" style={heroStyle}><div className="max-w-7xl mx-auto px-4 grid lg:grid-cols-[1fr_420px] gap-10 items-center"><div className="max-w-2xl"><p className="font-mono text-xs tracking-widest uppercase text-accent mb-3">{page.eyebrow}</p><h1 className="font-display font-900 text-4xl lg:text-5xl mb-4">{page.heading} <em className="not-italic text-accent">{page.accent}</em></h1><Paragraphs text={page.body} className="text-gray-300 text-lg leading-relaxed mb-8 space-y-3" /><div className="flex flex-wrap gap-3"><Link href={page.primaryHref} className="btn-primary">{page.primaryLabel}</Link><Link href={page.secondaryHref} className="border border-white/30 text-white font-display font-600 px-5 py-2.5 rounded hover:border-white transition-colors">{page.secondaryLabel}</Link></div></div>{page.heroImageUrl && <div className="hidden lg:block bg-white/5 border border-white/10 rounded-2xl p-3"><img src={page.heroImageUrl} alt={page.eyebrow} className="w-full h-80 object-cover rounded-xl"/></div>}</div></section>
    {contact && <section className="py-8 bg-gray-50 border-y border-gray-200"><div className="max-w-7xl mx-auto px-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-4 text-sm"><a className="bg-white border border-gray-200 rounded-xl p-4 hover:border-accent" href={`mailto:${contact.salesEmail}`}><strong className="block text-navy-900">Order’s/Quotes</strong><span className="text-gray-500">{contact.salesEmail}</span></a><a className="bg-white border border-gray-200 rounded-xl p-4 hover:border-accent" href={`mailto:${contact.infoEmail}`}><strong className="block text-navy-900">General/Media Inquiries</strong><span className="text-gray-500">{contact.infoEmail}</span></a><a className="bg-white border border-gray-200 rounded-xl p-4 hover:border-accent" href={`tel:${contact.phone}`}><strong className="block text-navy-900">Phone</strong><span className="text-gray-500">{contact.phone}</span></a><div className="bg-white border border-gray-200 rounded-xl p-4"><strong className="block text-navy-900">Location</strong><span className="text-gray-500">{contact.location}</span></div></div></section>}
    <section className="py-14 bg-white"><div className="max-w-7xl mx-auto px-4"><p className="section-label">{page.sectionEyebrow}</p><h2 className="section-heading text-3xl mb-2">{page.sectionHeading}</h2><Paragraphs text={page.sectionBody} className="text-gray-500 mb-8 text-sm max-w-3xl leading-relaxed space-y-3" />{page.blocks.length > 0 && <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{page.blocks.map((b,i)=><div key={`${b.title}-${i}`} className="border border-gray-200 rounded-xl p-6 hover:border-accent/40 hover:shadow-sm transition-all">{b.imageUrl ? <img src={b.imageUrl} alt={b.title} className="w-full h-32 object-cover rounded-lg mb-4"/> : <div className="text-2xl mb-3">{b.icon}</div>}<h3 className="font-display font-700 text-navy-900 mb-1">{b.title}</h3><p className="text-accent text-xs font-600 mb-2">{b.subtitle}</p><p className="text-gray-500 text-xs leading-relaxed mb-4">{b.body}</p>{b.linkLabel && <Link href={b.linkHref || "#"} className="text-accent font-display font-700 text-xs hover:text-accent-dark">{b.linkLabel} →</Link>}</div>)}</div>}</div></section>
    {page.steps.length > 0 && <section className="py-14 bg-gray-50"><div className="max-w-7xl mx-auto px-4"><p className="section-label">Process</p><h2 className="section-heading text-3xl mb-8">How it works.</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{page.steps.map((s,i)=><div key={`${s.number}-${i}`} className="bg-white border border-gray-200 rounded-lg p-5">{s.imageUrl && <img src={s.imageUrl} alt={s.title} className="w-full h-28 object-cover rounded mb-4"/>}<div className="font-mono text-accent text-xs mb-3">{s.number}</div><h3 className="font-display font-700 text-navy-900 mb-2">{s.title}</h3><p className="text-gray-500 text-xs leading-relaxed">{s.body}</p></div>)}</div></div></section>}
    {children ? <section id="request" className="py-14 bg-white"><div className="max-w-3xl mx-auto px-4"><p className="section-label">Get Started</p><h2 className="section-heading text-3xl mb-2">{formTitle || page.ctaHeading}</h2><Paragraphs text={page.ctaBody} className="text-gray-500 mb-8 text-sm space-y-2" />{children}</div></section> : <section className="py-12 bg-accent"><div className="max-w-3xl mx-auto px-4 text-center"><h2 className="font-display font-900 text-3xl text-navy-900 mb-3">{page.ctaHeading}</h2><Paragraphs text={page.ctaBody} className="text-navy-800 mb-6 text-sm space-y-2" /><div className="flex flex-wrap justify-center gap-3"><Link href={page.ctaPrimaryHref} className="bg-navy-900 text-white font-display font-700 px-6 py-3 rounded hover:bg-navy-800 transition-colors">{page.ctaPrimaryLabel}</Link><Link href={page.ctaSecondaryHref} className="bg-white/25 border border-navy-900/20 text-navy-900 font-display font-700 px-6 py-3 rounded hover:bg-white/40 transition-colors">{page.ctaSecondaryLabel}</Link></div></div></section>}
  </>;
}
