import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { isDatabaseConfigured } from "@/lib/db";
export const dynamic="force-dynamic";
async function user(){const s=await getServerSession(authOptions); if(!s?.user?.email)return null; if(!isDatabaseConfigured())return {id:"preview",email:s.user.email,name:s.user.name||"",phone:"",company:"",addresses:[]} as any; return prisma.user.findUnique({where:{email:s.user.email.toLowerCase()},include:{addresses:{orderBy:[{isPrimary:"desc"},{createdAt:"asc"}]}}});}
function clean(b:any){const address1=String(b?.address1||"").trim(),city=String(b?.city||b?.town||"").trim(),postcode=String(b?.postcode||"").trim(),country=String(b?.country||"United Kingdom").trim(); if(!address1||!city||!postcode||!country)throw new Error("Address line 1, town/city, postcode and country are required."); return {label:String(b?.label||"").trim()||null,fullName:String(b?.fullName||"").trim()||null,company:String(b?.company||"").trim()||null,phone:String(b?.phone||"").trim()||null,address1,address2:String(b?.address2||"").trim()||null,city,postcode,country,isPrimary:Boolean(b?.isPrimary)};}
export async function GET(){const u=await user(); if(!u)return NextResponse.json({ok:false,error:"Please sign in."},{status:401}); return NextResponse.json({ok:true,customer:{name:u.name||"",email:u.email||"",phone:u.phone||"",company:u.company||""},addresses:u.addresses||[]});}
export async function POST(r:Request){const u=await user(); if(!u)return NextResponse.json({ok:false,error:"Please sign in."},{status:401}); try{const data=clean(await r.json().catch(()=>({}))); if(u.id==="preview")return NextResponse.json({ok:true,address:{id:"preview",...data}}); const count=await prisma.customerAddress.count({where:{userId:u.id}}); if(count>=5)return NextResponse.json({ok:false,error:"You can save up to 5 addresses."},{status:400}); const makePrimary=data.isPrimary||count===0; const address=await prisma.$transaction(async tx=>{if(makePrimary)await tx.customerAddress.updateMany({where:{userId:u.id},data:{isPrimary:false}}); return tx.customerAddress.create({data:{...data,isPrimary:makePrimary,userId:u.id}});}); return NextResponse.json({ok:true,address});}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Could not save address."},{status:400});}}
